version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  fraud-detector:
    build: .
    depends_on:
      - kafka
      - redis
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_TOPIC=transactions
      - KAFKA_ALERTS_TOPIC=fraud-alerts
      - KAFKA_GROUP_ID=fraud-detector-group

ml-service:
  build:
    context: ./ml-service
    dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    depends_on:
      - redis
